#include <QtTest/QtTest>
#include <QSignalSpy>
#include <QTemporaryDir>
#include "../../src/business/sharemanager.h"
#include "../../src/business/mountmanager.h"
#include "../../src/business/networkdiscovery.h"
#include "../../src/core/shareconfiguration.h"
#include "../../src/core/permissionset.h"
#include "../../src/core/remotenfsshare.h"

using namespace NFSShareManager;

/**
 * @brief Integration test for business logic components
 * 
 * This test verifies that ShareManager, MountManager, and NetworkDiscovery
 * work together properly and can be integrated into the main application.
 */
class BusinessIntegrationTest : public QObject
{
    Q_OBJECT

private slots:
    void initTestCase();
    void cleanupTestCase();
    void init();
    void cleanup();

    // Integration tests
    void testComponentInitialization();
    void testShareManagerIntegration();
    void testMountManagerIntegration();
    void testNetworkDiscoveryIntegration();
    void testComponentInteraction();

private:
    ShareManager *m_shareManager;
    MountManager *m_mountManager;
    NetworkDiscovery *m_networkDiscovery;
    QTemporaryDir *m_tempDir;
    QString m_testPath;
};

void BusinessIntegrationTest::initTestCase()
{
    // Create temporary directory for testing
    m_tempDir = new QTemporaryDir(QDir::homePath() + "/test_integration_XXXXXX");
    QVERIFY(m_tempDir->isValid());
    m_testPath = m_tempDir->path() + "/test_share";
    
    // Create test directory
    QDir().mkpath(m_testPath);
    QVERIFY(QFileInfo(m_testPath).exists());
}

void BusinessIntegrationTest::cleanupTestCase()
{
    delete m_tempDir;
}

void BusinessIntegrationTest::init()
{
    // Initialize all business logic components
    m_shareManager = new ShareManager(this);
    m_mountManager = new MountManager(this);
    m_networkDiscovery = new NetworkDiscovery(this);
    
    QVERIFY(m_shareManager != nullptr);
    QVERIFY(m_mountManager != nullptr);
    QVERIFY(m_networkDiscovery != nullptr);
}

void BusinessIntegrationTest::cleanup()
{
    delete m_shareManager;
    delete m_mountManager;
    delete m_networkDiscovery;
    
    m_shareManager = nullptr;
    m_mountManager = nullptr;
    m_networkDiscovery = nullptr;
}

void BusinessIntegrationTest::testComponentInitialization()
{
    // Test that all components initialize correctly
    QVERIFY(m_shareManager != nullptr);
    QVERIFY(m_mountManager != nullptr);
    QVERIFY(m_networkDiscovery != nullptr);
    
    // Test initial states
    QVERIFY(m_shareManager->getActiveShares().isEmpty());
    QVERIFY(m_mountManager->getManagedMounts().isEmpty());
    QVERIFY(!m_networkDiscovery->isDiscoveryActive());
    QCOMPARE(m_networkDiscovery->discoveryStatus(), NetworkDiscovery::DiscoveryStatus::Idle);
}

void BusinessIntegrationTest::testShareManagerIntegration()
{
    // Test ShareManager functionality
    QVERIFY(m_shareManager->validateSharePath(m_testPath));
    
    // Test that we can create a valid configuration
    ShareConfiguration config("Test Share", AccessMode::ReadWrite);
    config.setAllowedHosts(QStringList() << "192.168.1.0/24");
    QVERIFY(config.isValid());
    
    // Test permission set
    PermissionSet permissions(AccessMode::ReadWrite);
    permissions.setHostPermission("192.168.1.100", AccessMode::ReadOnly);
    QVERIFY(permissions.isValid());
    
    // Test exports file generation
    QString exportsContent = m_shareManager->generateExportsFileContent();
    QVERIFY(!exportsContent.isEmpty());
    QVERIFY(exportsContent.contains("# Generated by NFS Share Manager"));
}

void BusinessIntegrationTest::testMountManagerIntegration()
{
    // Test MountManager functionality
    QString testMountPoint = m_tempDir->path() + "/test_mount";
    
    // Test mount point validation
    QVERIFY(m_mountManager->validateMountPoint(testMountPoint));
    
    // Test mount point creation
    QVERIFY(m_mountManager->createMountPoint(testMountPoint));
    QVERIFY(m_mountManager->isMountPointSuitable(testMountPoint));
    
    // Test default mount options
    RemoteNFSShare testShare;
    testShare.setHostName("testserver");
    testShare.setHostAddress(QHostAddress("192.168.1.100"));
    testShare.setExportPath("/export/test");
    testShare.setSupportedVersion(NFSVersion::Version4);
    
    MountOptions options = m_mountManager->getDefaultMountOptions(testShare);
    QCOMPARE(options.nfsVersion, NFSVersion::Version4);
    QVERIFY(options.isValid());
}

void BusinessIntegrationTest::testNetworkDiscoveryIntegration()
{
    // Test NetworkDiscovery functionality
    QVERIFY(!m_networkDiscovery->isDiscoveryActive());
    QCOMPARE(m_networkDiscovery->scanInterval(), 30000);
    QCOMPARE(m_networkDiscovery->scanMode(), NetworkDiscovery::ScanMode::Quick);
    
    // Test target host management
    m_networkDiscovery->addTargetHost("192.168.1.100");
    QVERIFY(m_networkDiscovery->getTargetHosts().contains("192.168.1.100"));
    
    m_networkDiscovery->removeTargetHost("192.168.1.100");
    QVERIFY(!m_networkDiscovery->getTargetHosts().contains("192.168.1.100"));
    
    // Test scan statistics
    QHash<QString, QVariant> stats = m_networkDiscovery->getScanStatistics();
    QVERIFY(stats.contains("total_scans"));
    QCOMPARE(stats["total_scans"].toInt(), 0);
}

void BusinessIntegrationTest::testComponentInteraction()
{
    // Test that components can work together
    
    // 1. Set up network discovery to find shares
    QSignalSpy discoveryStartedSpy(m_networkDiscovery, &NetworkDiscovery::discoveryStarted);
    QSignalSpy discoveryCompletedSpy(m_networkDiscovery, &NetworkDiscovery::discoveryCompleted);
    
    m_networkDiscovery->addTargetHost("127.0.0.1");
    m_networkDiscovery->refreshDiscovery(NetworkDiscovery::ScanMode::Targeted);
    
    // Wait for discovery to complete
    QTRY_VERIFY_WITH_TIMEOUT(discoveryCompletedSpy.count() >= 1, 15000);
    
    // 2. Test that ShareManager can handle share configurations
    ShareConfiguration config("Integration Test Share", AccessMode::ReadWrite);
    config.setAllowedHosts(QStringList() << "192.168.1.0/24");
    
    PermissionSet permissions(AccessMode::ReadWrite);
    permissions.setHostPermission("192.168.1.100", AccessMode::ReadOnly);
    permissions.setEnableRootSquash(true);
    
    QVERIFY(config.isValid());
    QVERIFY(permissions.isValid());
    
    // 3. Test that MountManager can handle mount configurations
    RemoteNFSShare remoteShare;
    remoteShare.setHostName("testserver");
    remoteShare.setHostAddress(QHostAddress("192.168.1.100"));
    remoteShare.setExportPath("/export/test");
    remoteShare.setSupportedVersion(NFSVersion::Version4);
    
    QString mountPoint = m_tempDir->path() + "/integration_mount";
    MountOptions mountOptions = m_mountManager->getDefaultMountOptions(remoteShare);
    
    QVERIFY(remoteShare.isValid());
    QVERIFY(m_mountManager->validateMountPoint(mountPoint));
    QVERIFY(mountOptions.isValid());
    
    // 4. Verify that all components maintain their state correctly
    QVERIFY(m_shareManager->getActiveShares().isEmpty());
    QVERIFY(m_mountManager->getManagedMounts().isEmpty());
    QVERIFY(m_networkDiscovery->getDiscoveredShares().size() >= 0); // May have found shares
    
    // 5. Test error handling integration
    QStringList shareErrors = m_shareManager->getPathValidationErrors("/nonexistent/path");
    QVERIFY(!shareErrors.isEmpty());
    
    QStringList mountErrors = m_mountManager->getMountPointValidationErrors("");
    QVERIFY(!mountErrors.isEmpty());
}

QTEST_MAIN(BusinessIntegrationTest)
#include "test_business_integration.moc"